package news.analytics.pipeline.config;

import java.util.List;

/**
 * Defines configuration which tells the parser, how to extracts the required details from the raw html.
 * Each News Agency will have its configuration instance.
 */
public class NewsMetaConfig {

    public NewsMetaConfig() {
    }

    /**
     * Charset of the page
     */
    private TagLocator charset;

    /**
     * Name of the News provider agency
     */
    private String newsAgencyName;

    /**
     * Tag keeping title of the article, generally only one per news item
     */
    private TagLocator title;

    /**
     * Plain text of the actual news article
     * Generally in one tag but can occur divided in multiple tags.
     */
    private List<TagLocator> content;

    /**
     * Usually, news websites add tags to each news. This tag will locates such values from the current news item.
     */
    private List<TagLocator> keywords;

    /**
     * There could be lots of h1 which may contain unnecessary information like advertise.
     * Also, there could be multiple h1 providing real necessary information
     */
    private List<TagLocator> h1;

    /**
     * Generally h2 maintains section headers.
     * There could be lots of h2 which may contain unnecessary information like advertise.
     * Also, there could be multiple h2 providing real necessary information
     */
    private List<TagLocator> h2;

    /**
     * HTML Tags which maintains categories of RawNews
     */
    private List<TagLocator> tags;

    /**
     * Tag keeping the description about the news article. Its generally the snippet generated by news agency itself.
     */
    private TagLocator description;

    private TagLocator publishDate;
    private TagLocator modifiedDate;
    private TagLocator creationDate;

    /**
     * Every site mentions the news author. This tag locates the author name.
     */
    private TagLocator author;

    public String getNewsAgencyName() {
        return newsAgencyName;
    }

    public void setNewsAgencyName(String newsAgencyName) {
        this.newsAgencyName = newsAgencyName;
    }

    public TagLocator getTitle() {
        return title;
    }

    public void setTitle(TagLocator title) {
        this.title = title;
    }

    public List<TagLocator> getContent() {
        return content;
    }

    public void setContent(List<TagLocator> content) {
        this.content = content;
    }

    public List<TagLocator> getKeywords() {
        return keywords;
    }

    public void setKeywords(List<TagLocator> keywords) {
        this.keywords = keywords;
    }

    public List<TagLocator> getH1() {
        return h1;
    }

    public void setH1(List<TagLocator> h1) {
        this.h1 = h1;
    }

    public List<TagLocator> getH2() {
        return h2;
    }

    public void setH2(List<TagLocator> h2) {
        this.h2 = h2;
    }

    public List<TagLocator> getTags() {
        return tags;
    }

    public void setTags(List<TagLocator> tags) {
        this.tags = tags;
    }

    public TagLocator getDescription() {
        return description;
    }

    public void setDescription(TagLocator description) {
        this.description = description;
    }

    public TagLocator getPublishDate() {
        return publishDate;
    }

    public void setPublishDate(TagLocator publishDate) {
        this.publishDate = publishDate;
    }

    public TagLocator getModifiedDate() {
        return modifiedDate;
    }

    public void setModifiedDate(TagLocator modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    public TagLocator getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(TagLocator creationDate) {
        this.creationDate = creationDate;
    }

    public TagLocator getAuthor() {
        return author;
    }

    public void setAuthor(TagLocator author) {
        this.author = author;
    }

    public TagLocator getCharset() {
        return charset;
    }

    public void setCharset(TagLocator charset) {
        this.charset = charset;
    }
}
