CREATE TABLE "RAW_NEWS" ("ID" BIGINT PRIMARY KEY,"URI" VARCHAR2(500 CHAR) NOT NULL, "NEWS_AGENCY" VARCHAR2(250 CHAR), "RAW_CONTENT" CLOB);
INSERT INTO RAW_NEWS (ID, URI, NEWS_AGENCY, RAW_CONTENT) VALUES (1, 'http://news.analytics.test.com', 'The Hindu', 'Raw HTML');
CREATE TABLE "SEEDS" ("ID" BIGINT PRIMARY KEY, "URI" VARCHAR2(500 CHAR) NOT NULL, "FETCH_STATUS" VARCHAR2(250 CHAR), "HTTP_CODE" INT);
