CREATE TABLE "RAW_NEWS" ("ID" BIGINT PRIMARY KEY,"URI" VARCHAR2(500 CHAR) NOT NULL, "NEWS_AGENCY" VARCHAR2(250 CHAR), "RAW_CONTENT" CLOB, "PROCESS_STATUS" VARCHAR);
CREATE TABLE "SEEDS" ("ID" BIGINT PRIMARY KEY, "URI" VARCHAR2(500 CHAR) NOT NULL, "FETCH_STATUS" VARCHAR2(250 CHAR), "HTTP_CODE" INT);
