CREATE TABLE IF NOT EXISTS "SEEDS"
(
"ID" BIGINT PRIMARY KEY,
"URI" VARCHAR2(500 CHAR) NOT NULL,
"FETCH_STATUS" VARCHAR2(250 CHAR),
"HTTP_CODE" INT
);

CREATE TABLE IF NOT EXISTS "RAW_NEWS"
(
"ID" BIGINT PRIMARY KEY,
"URI" VARCHAR2(500 CHAR) NOT NULL,
"NEWS_AGENCY" VARCHAR2(250 CHAR),
"RAW_CONTENT" CLOB,
"PROCESS_STATUS" VARCHAR2(250 CHAR)
);

CREATE TABLE IF NOT EXISTS "TRANSFORMED_NEWS"
(
"ID" BIGINT PRIMARY KEY,
"URI" VARCHAR2(500 CHAR) NOT NULL,
"NEWS_AGENCY" VARCHAR2(250 CHAR)NOT NULL,
"CHARSET" VARCHAR2(100 CHAR),
"SECTION" VARCHAR2(500 CHAR),
"TITLE" VARCHAR2(1000 CHAR) NOT NULL,
"CONTENT" CLOB,
"KEYWORDS" VARCHAR2(1000 CHAR),
"H1" VARCHAR2(1000 CHAR),
"H2" VARCHAR2(1000 CHAR),
"SNIPPET" CLOB,
"PUBLISH_DATE" BIGINT,
"MODIFIED_DATE" BIGINT,
"CREATION_DATE" BIGINT,
"AUTHOR" VARCHAR2(500 CHAR),
"PLAIN_TEXT" CLOB,
"CITY" VARCHAR2(250 CHAR),
"PROCESS_STATUS" VARCHAR2(250 CHAR)
);

CREATE TABLE IF NOT EXISTS "ANALYZED_NEWS"
(
"ID" BIGINT PRIMARY KEY,
"URI" VARCHAR2(500 CHAR) NOT NULL,
"NEWS_AGENCY" VARCHAR2(250 CHAR)NOT NULL,
"CHARSET" VARCHAR2(100 CHAR),
"SECTION" VARCHAR2(500 CHAR),
"TITLE" VARCHAR2(1000 CHAR) NOT NULL,
"CONTENT" CLOB,
"KEYWORDS" VARCHAR2(1000 CHAR),
"H1" VARCHAR2(1000 CHAR),
"H2" VARCHAR2(1000 CHAR),
"SNIPPET" CLOB,
"PUBLISH_DATE" BIGINT,
"MODIFIED_DATE" BIGINT,
"CREATION_DATE" BIGINT,
"AUTHOR" VARCHAR2(500 CHAR),
"PLAIN_TEXT" CLOB,
"PROCESS_STATUS" VARCHAR2(250 CHAR),
"SENTIMENT_SCORE" FLOAT,
"PRIMARY_TAGS" VARCHAR2(1000 CHAR),
"CITY" VARCHAR2(250 CHAR),
"SECONDARY_TAGS" VARCHAR2(1000 CHAR)
);

CREATE INDEX IF NOT EXISTS SEEDS_INDEX ON SEEDS(ID);
CREATE INDEX IF NOT EXISTS RAW_NEWS_INDEX ON RAW_NEWS(ID);
CREATE INDEX IF NOT EXISTS RANSFORMED_NEWS_INDEX ON TRANSFORMED_NEWS(ID);
CREATE INDEX IF NOT EXISTS ANALYZED_NEWS_INDEX ON ANALYZED_NEWS(ID);
