package news.analytics.parser.config;

import java.util.List;

/**
 * Defines configuration which tells the parser, how to extracts the required details from the raw html.
 * Each News Agency will have its configuration instance.
 */
public class NewsMetaConfig {

    public NewsMetaConfig() {
    }

    /**
     * Name of the News provider agency
     */
    private String newsAgencyName;

    /**
     * Tag keeping title of the article, generally only one per news item
     */
    private Tag title;

    /**
     * Plain text of the actual news article
     * Generally in one tag but can occur divided in multiple tags.
     */
    private List<Tag> content;

    /**
     * Usually, news websites add tags to each news. This tag will locates such values from the current news item.
     */
    private List<Tag> keywords;

    /**
     * There could be lots of h1 which may contain unnecessary information like advertise.
     * Also, there could be multiple h1 providing real necessary information
     */
    private List<Tag> h1;

    /**
     * Generally h2 maintains section headers.
     * There could be lots of h2 which may contain unnecessary information like advertise.
     * Also, there could be multiple h2 providing real necessary information
     */
    private List<Tag> h2;

    /**
     * HTML Tags which maintains tags or categories of RawNews
     */
    private List<Tag> tags;

    /**
     * Tag keeping the description about the news article. Its generally the snippet generated by news agency itself.
     */
    private Tag description;

    private Tag publishDate;
    private Tag modifiedDate;
    private Tag creationDate;

    /**
     * Every site mentions the news author. This tag locates the author name.
     */
    private Tag author;

    public String getNewsAgencyName() {
        return newsAgencyName;
    }

    public void setNewsAgencyName(String newsAgencyName) {
        this.newsAgencyName = newsAgencyName;
    }

    public Tag getTitle() {
        return title;
    }

    public void setTitle(Tag title) {
        this.title = title;
    }

    public List<Tag> getContent() {
        return content;
    }

    public void setContent(List<Tag> content) {
        this.content = content;
    }

    public List<Tag> getKeywords() {
        return keywords;
    }

    public void setKeywords(List<Tag> keywords) {
        this.keywords = keywords;
    }

    public List<Tag> getH1() {
        return h1;
    }

    public void setH1(List<Tag> h1) {
        this.h1 = h1;
    }

    public List<Tag> getH2() {
        return h2;
    }

    public void setH2(List<Tag> h2) {
        this.h2 = h2;
    }

    public List<Tag> getTags() {
        return tags;
    }

    public void setTags(List<Tag> tags) {
        this.tags = tags;
    }

    public Tag getDescription() {
        return description;
    }

    public void setDescription(Tag description) {
        this.description = description;
    }

    public Tag getPublishDate() {
        return publishDate;
    }

    public void setPublishDate(Tag publishDate) {
        this.publishDate = publishDate;
    }

    public Tag getModifiedDate() {
        return modifiedDate;
    }

    public void setModifiedDate(Tag modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    public Tag getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Tag creationDate) {
        this.creationDate = creationDate;
    }

    public Tag getAuthor() {
        return author;
    }

    public void setAuthor(Tag author) {
        this.author = author;
    }
}
